// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetAvengers.Models;

namespace ProjetAvengers.Migrations
{
    [DbContext(typeof(AvengersContext))]
    [Migration("20200417123329_AjoutBleuRougeVert")]
    partial class AjoutBleuRougeVert
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetAvengers.Models.Bleu.Modules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom_module")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Bleu.Privileges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ecriture")
                        .HasColumnType("bit");

                    b.Property<bool>("Lecture")
                        .HasColumnType("bit");

                    b.Property<bool>("Modification")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Suppression")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Privileges");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Bleu.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mot_de_passe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Civils", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Civilite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_de_deces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_de_naissance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Derniere_modification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationalite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone_portable")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Civils");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Coordonnee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Civils_IdId")
                        .HasColumnType("int");

                    b.Property<int>("Code_Postal")
                        .HasColumnType("int");

                    b.Property<bool>("Est_Principale")
                        .HasColumnType("bit");

                    b.Property<int>("Numero_de_voie")
                        .HasColumnType("int");

                    b.Property<int?>("Organisation_IdId")
                        .HasColumnType("int");

                    b.Property<string>("Pays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone_fixe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Civils_IdId");

                    b.HasIndex("Organisation_IdId");

                    b.ToTable("Coordonnee");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Crise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Incident_majeur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Litige")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Crise");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Incidents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_crise")
                        .HasColumnType("int");

                    b.Property<int>("Id_litige")
                        .HasColumnType("int");

                    b.Property<string>("Identite_origine_appel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lieu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Liste_sh_crise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_crise")
                        .HasColumnType("int");

                    b.Property<int>("Id_superhero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Liste_sh_crise");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Liste_sv_crise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_crise")
                        .HasColumnType("int");

                    b.Property<int>("Id_supervilain")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Liste_sv_crise");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Litige", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Objet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type_litige")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Litige");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Membre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CivilsId")
                        .HasColumnType("int");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CivilsId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Membre");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Organisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_de_creation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Derniere_modification")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Dirigeant")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone_Portable")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Dirigeant")
                        .IsUnique()
                        .HasFilter("[Dirigeant] IS NOT NULL");

                    b.ToTable("Organisation");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Super_Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Identite")
                        .HasColumnType("int");

                    b.Property<int?>("Liste_SuperHero_MissionId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Point_faible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pouvoir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Identite")
                        .IsUnique()
                        .HasFilter("[Identite] IS NOT NULL");

                    b.HasIndex("Liste_SuperHero_MissionId");

                    b.ToTable("Super_Hero");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Super_Vilain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Identite")
                        .HasColumnType("int");

                    b.Property<int?>("Liste_SuperVilain_MissionId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Point_faible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pouvoir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Identite")
                        .IsUnique()
                        .HasFilter("[Identite] IS NOT NULL");

                    b.HasIndex("Liste_SuperVilain_MissionId");

                    b.ToTable("Super_Vilain");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Vert.Liste_SuperHero_Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Liste_SuperHero_Mission");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Vert.Liste_SuperVilain_Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Liste_SuperVilain_Mission");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Vert.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_debut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_fin")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gravite")
                        .HasColumnType("int");

                    b.Property<string>("Itineraire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Liste_SuperHero_MissionId")
                        .HasColumnType("int");

                    b.Property<int?>("Liste_SuperVilain_MissionId")
                        .HasColumnType("int");

                    b.Property<string>("Nature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Liste_SuperHero_MissionId");

                    b.HasIndex("Liste_SuperVilain_MissionId");

                    b.ToTable("Mission");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Vert.Rapport_Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Detail_intervention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MissionId")
                        .HasColumnType("int");

                    b.Property<string>("Nouveau_Civil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vilain_intervention")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.ToTable("Rapport_Mission");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Vert.Satisfaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cible")
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fichiers")
                        .HasColumnType("int");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<int?>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.Property<int>("Type_litige")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.ToTable("Satisfaction");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Coordonnee", b =>
                {
                    b.HasOne("ProjetAvengers.Models.Civils", "Civils_Id")
                        .WithMany("Coordonnees")
                        .HasForeignKey("Civils_IdId");

                    b.HasOne("ProjetAvengers.Models.Organisation", "Organisation_Id")
                        .WithMany("Coordonnees")
                        .HasForeignKey("Organisation_IdId");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Membre", b =>
                {
                    b.HasOne("ProjetAvengers.Models.Civils", "Civils")
                        .WithMany("Membres")
                        .HasForeignKey("CivilsId");

                    b.HasOne("ProjetAvengers.Models.Organisation", "Organisation")
                        .WithMany("Membres")
                        .HasForeignKey("OrganisationId");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Organisation", b =>
                {
                    b.HasOne("ProjetAvengers.Models.Civils", "Civils_Id")
                        .WithOne("Dirigeant")
                        .HasForeignKey("ProjetAvengers.Models.Organisation", "Dirigeant");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Super_Hero", b =>
                {
                    b.HasOne("ProjetAvengers.Models.Civils", "Civils_Id")
                        .WithOne("Super_Hero")
                        .HasForeignKey("ProjetAvengers.Models.Super_Hero", "Identite");

                    b.HasOne("ProjetAvengers.Models.Vert.Liste_SuperHero_Mission", null)
                        .WithMany("Super_Heros")
                        .HasForeignKey("Liste_SuperHero_MissionId");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Super_Vilain", b =>
                {
                    b.HasOne("ProjetAvengers.Models.Civils", "Civils_Id")
                        .WithOne("Super_Vilain")
                        .HasForeignKey("ProjetAvengers.Models.Super_Vilain", "Identite");

                    b.HasOne("ProjetAvengers.Models.Vert.Liste_SuperVilain_Mission", null)
                        .WithMany("Super_Vilains")
                        .HasForeignKey("Liste_SuperVilain_MissionId");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Vert.Mission", b =>
                {
                    b.HasOne("ProjetAvengers.Models.Vert.Liste_SuperHero_Mission", null)
                        .WithMany("Missions")
                        .HasForeignKey("Liste_SuperHero_MissionId");

                    b.HasOne("ProjetAvengers.Models.Vert.Liste_SuperVilain_Mission", null)
                        .WithMany("Missions")
                        .HasForeignKey("Liste_SuperVilain_MissionId");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Vert.Rapport_Mission", b =>
                {
                    b.HasOne("ProjetAvengers.Models.Vert.Mission", null)
                        .WithMany("Rapport_Missions")
                        .HasForeignKey("MissionId");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Vert.Satisfaction", b =>
                {
                    b.HasOne("ProjetAvengers.Models.Vert.Mission", null)
                        .WithMany("Satisfactions")
                        .HasForeignKey("MissionId");
                });
#pragma warning restore 612, 618
        }
    }
}
