// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetAvengers.Models;

namespace ProjetAvengers.Migrations
{
    [DbContext(typeof(AvengersContext))]
    partial class AvengersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetAvengers.Models.Civils", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Civilite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date_de_deces")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_de_naissance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Derniere_modification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nationalite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone_portable")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Civils");
                });

            modelBuilder.Entity("ProjetAvengers.Models.CivilsDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Civilite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CivilsDTO");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Coordonnee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Civils_IdId")
                        .HasColumnType("int");

                    b.Property<int>("Code_Postal")
                        .HasColumnType("int");

                    b.Property<int>("Numero_de_voie")
                        .HasColumnType("int");

                    b.Property<int?>("Organisation_IdId")
                        .HasColumnType("int");

                    b.Property<string>("Pays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone_fixe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("est_Principale")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Civils_IdId");

                    b.HasIndex("Organisation_IdId");

                    b.ToTable("Coordonnee");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Membre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CivilsId")
                        .HasColumnType("int");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CivilsId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Membre");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Organisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_de_creation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Derniere_modification")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Dirigeant")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone_Portable")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Dirigeant")
                        .IsUnique()
                        .HasFilter("[Dirigeant] IS NOT NULL");

                    b.ToTable("Organisation");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Super_Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Identite")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("point_faible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pouvoir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Identite")
                        .IsUnique()
                        .HasFilter("[Identite] IS NOT NULL");

                    b.ToTable("Super_Hero");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Super_Vilain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Identite")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("point_faible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pouvoir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Identite")
                        .IsUnique()
                        .HasFilter("[Identite] IS NOT NULL");

                    b.ToTable("Super_Vilain");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Coordonnee", b =>
                {
                    b.HasOne("ProjetAvengers.Models.Civils", "Civils_Id")
                        .WithMany("Coordonnees")
                        .HasForeignKey("Civils_IdId");

                    b.HasOne("ProjetAvengers.Models.Organisation", "Organisation_Id")
                        .WithMany("Coordonnees")
                        .HasForeignKey("Organisation_IdId");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Membre", b =>
                {
                    b.HasOne("ProjetAvengers.Models.Civils", "Civils")
                        .WithMany("Membres")
                        .HasForeignKey("CivilsId");

                    b.HasOne("ProjetAvengers.Models.Organisation", "Organisation")
                        .WithMany("Membres")
                        .HasForeignKey("OrganisationId");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Organisation", b =>
                {
                    b.HasOne("ProjetAvengers.Models.Civils", "Civils_Id")
                        .WithOne("Dirigeant")
                        .HasForeignKey("ProjetAvengers.Models.Organisation", "Dirigeant");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Super_Hero", b =>
                {
                    b.HasOne("ProjetAvengers.Models.Civils", "Civils_Id")
                        .WithOne("Super_Hero")
                        .HasForeignKey("ProjetAvengers.Models.Super_Hero", "Identite");
                });

            modelBuilder.Entity("ProjetAvengers.Models.Super_Vilain", b =>
                {
                    b.HasOne("ProjetAvengers.Models.Civils", "Civils_Id")
                        .WithOne("Super_Vilain")
                        .HasForeignKey("ProjetAvengers.Models.Super_Vilain", "Identite");
                });
#pragma warning restore 612, 618
        }
    }
}
